#' Run the SickSicker State-Transition Model
#'
#' @description Run the SickSicker Markov model.
#'
#' @param age_init_ Numeric scalar, age at baseline. Default is 25.
#' @param age_max_ Numeric scalar, maximum age of follow up. Default is 55.
#' @param discount_rate_ Numeric scalar, discount rate for costs and QALYs.
#' Default is 0.035.
#' @param p_HD Numeric scalar, probability to die when healthy. Default is
#' 0.005.
#' @param p_HS1 Numeric scalar, probability to become sick when healthy. Default
#' is 0.15.
#' @param p_S1H Numeric scalar, probability to become healthy when sick. Default
#' is 0.5.
#' @param p_S1S2 Numeric scalar, probability to become sicker when sick. Default
#' is 0.105.
#' @param hr_S1 Numeric scalar, hazard ratio of death in sick vs healthy.
#' Default is 3.
#' @param hr_S2 Numeric scalar, hazard ratio of death in sicker vs healthy.
#' Default is 10.
#' @param c_H Numeric scalar, cost of remaining one cycle in the healthy state.
#' Default is 2000.
#' @param c_S1 Numeric scalar, cost of remaining one cycle in the sick state.
#' Default is 4000.
#' @param c_S2 Numeric scalar, cost of remaining one cycle in the sicker state.
#' Default is 15000.
#' @param c_Trt Numeric scalar, cost of treatment(per cycle). Default is 12000.
#' @param c_D Numeric scalar, cost of being in the death state. Default is 0.
#' @param u_H Numeric scalar, utility when healthy. Default is 1.
#' @param u_S1 Numeric scalar, utility when sick. Default is 0.75.
#' @param u_S2 Numeric scalar, utility when sicker. Default is 0.5.
#' @param u_D Numeric scalar, utility when dead. Default is 0.
#' @param u_Trt Numeric scalar, utility when being treated. Default is 0.95.
#'
#' @return A matrix containing the costs and QALYs generated by running the
#' SickSicker model.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' library("sicksickerPack")
#' sickSicker_model_results <- run_sickSicker_model()
#' }
run_sickSicker_model <- function(
    age_init_ = 25,
    age_max_  = 55,
    discount_rate_ = 0.035,
    p_HD    = 0.005,
    p_HS1   = 0.15,
    p_S1H   = 0.5,
    p_S1S2  = 0.105,
    hr_S1   = 3,
    hr_S2   = 10,
    c_H     = 2000,
    c_S1    = 4000,
    c_S2    = 15000,
    c_Trt   = 12000,
    c_D     = 0,
    u_H     = 1,
    u_S1    = 0.75,
    u_S2    = 0.5,
    u_D     = 0,
    u_Trt   = 0.95
) {
  ## Calculate interim parameters:

  # strategy names
  Strategies = c("No Treatment", "Treatment")

  # time horizon, number of cycles
  time_horizon = age_max_ - age_init_
  # the 4 states of the model: Healthy (H), Sick (S1), Sicker (S2), Dead (D)
  states_count  <- c("H", "S1", "S2", "D")

  # rate of death in healthy
  r_HD    <- - log(1 - p_HD)
  # rate of death in sick
  r_S1D   <- hr_S1 * r_HD
  # rate of death in sicker
  r_S2D   <- hr_S2 * r_HD

  # probability of death in sick
  p_S1D   <- 1 - exp(-r_S1D)
  # probability of death in sicker
  p_S2D   <- 1 - exp(-r_S2D)

  # initial Markov trace
  initial_trace <- c("H" = 1, "S1" = 0, "S2" = 0, "D" = 0)

  # create vectors for the costs and utility of each treatment group
  c_trt    <- c("H" = c_H, "S1" = c_S1 + c_Trt, "S2" = c_S2 + c_Trt, "D" = c_D)
  c_no_trt <- c("H" = c_H, "S1" = c_S1, "S2" = c_S2, "D" = c_D)
  u_trt    <- c("H" = u_H, "S1" = u_Trt, "S2" = u_S2, "D" = u_D)
  u_no_trt <- c("H" = u_H, "S1" = u_S1, "S2" = u_S2, "D" = u_D)

  ## Calculate the discount weight for each cycle:

  discounting_weights <- calculate_discounting_weights(
    discount_rate_ = discount_rate_,
    time_horizon_ = time_horizon,
    first_cycle_ = TRUE)

  ## Define the model's transition matirix:

  transition_matrix <- define_transition_matrix(
    states_nms_ = states_count,
    tranistion_probs_ = c(
      1 - (p_HS1 + p_HD),                        p_HS1,         0,  p_HD,
      p_S1H,              1 - (p_S1H + p_S1S2 + p_S1D),    p_S1S2, p_S1D,
      0,                                             0, 1 - p_S2D, p_S2D,
      0,                                             0,         0,     1
    )
  )

  ## Create the model's Markov trace:

  Markov_trace <- create_Markov_trace(
    transition_matrix_ = transition_matrix,
    time_horizon_ = time_horizon,
    states_nms_ = states_count,
    initial_trace_ = initial_trace
  )

  ## Calculate costs:

  v_C_no_trt <- calculate_costs(
    Markov_trace_ = Markov_trace,
    costs_ = c_no_trt,
    discounting_weights_ = discounting_weights
  )
  v_C_trt <- calculate_costs(
    Markov_trace_ = Markov_trace,
    costs_ = c_trt,
    discounting_weights_ = discounting_weights
  )
  total_c_no_trt <- sum(v_C_no_trt)
  total_c_trt    <- sum(v_C_trt)

  ## Calculate QALYs:

  v_E_no_trt <- calculate_QALYs(
    Markov_trace_ = Markov_trace,
    utilities_ = u_no_trt,
    discounting_weights_ = discounting_weights
  )
  v_E_trt <- calculate_QALYs(
    Markov_trace_ = Markov_trace,
    utilities_ = u_trt,
    discounting_weights_ = discounting_weights
  )
  total_e_no_trt <- sum(v_E_no_trt)
  total_e_trt    <- sum(v_E_trt)

  ## Prepare results:
  ICER <- (total_c_no_trt - total_c_trt) / (total_e_no_trt - total_e_trt)

  results <- c(
    "Cost - no treatment"  = total_c_no_trt,
    "Cost - treatment"     = total_c_trt,
    "QALYs - no treatment" = total_e_no_trt,
    "QALYs - treatment"    = total_e_trt,
    "ICER" = ICER
  )

  return(results)
}
